//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DesktopIniManager.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DesktopIniManager.Properties.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   DesktopIniManager に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string App_ProductName {
            get {
                return ResourceManager.GetString("App_ProductName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DesktopIniManager could not start.
        ///
        ///{0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string App_StartFailed {
            get {
                return ResourceManager.GetString("App_StartFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   desktop.ini Manager に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string App_Title {
            get {
                return ResourceManager.GetString("App_Title", resourceCulture);
            }
        }
        public static string Main_ElevationTooltip
        {
            get { return StringOverlay.Get("Main_ElevationTooltip"); }
        }
        /// <summary>
        ///   An error occurred. The application can continue.
        ///
        ///{0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string App_Unhandled {
            get {
                return ResourceManager.GetString("App_Unhandled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Use configuration names separated by semicolons (for example Debug;Release). に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Clean_BadConfiguration {
            get {
                return ResourceManager.GetString("Clean_BadConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   MSBuild was not found. Install Visual Studio or Build Tools with MSBuild. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Clean_MsbuildMissing {
            get {
                return ResourceManager.GetString("Clean_MsbuildMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cannot clean the solution containing the running DIM application. Start DIM from a separate release folder outside this solution, then clean again. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Clean_RunningDim {
            get {
                return ResourceManager.GetString("Clean_RunningDim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Visual Studio Installer / vswhere.exe was not found. Install Visual Studio or Build Tools with MSBuild. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Clean_VswhereMissing {
            get {
                return ResourceManager.GetString("Clean_VswhereMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Browse に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Common_Browse {
            get {
                return ResourceManager.GetString("Common_Browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cancel に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Common_Cancel {
            get {
                return ResourceManager.GetString("Common_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Clean に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Common_Clean {
            get {
                return ResourceManager.GetString("Common_Clean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Clear に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Common_Clear {
            get {
                return ResourceManager.GetString("Common_Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Close に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Common_Close {
            get {
                return ResourceManager.GetString("Common_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Collapse に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Common_Collapse {
            get {
                return ResourceManager.GetString("Common_Collapse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Compare に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Common_Compare {
            get {
                return ResourceManager.GetString("Common_Compare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Expand に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Common_Expand {
            get {
                return ResourceManager.GetString("Common_Expand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   FAIL に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Common_Fail {
            get {
                return ResourceManager.GetString("Common_Fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   files に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Common_FilePlural {
            get {
                return ResourceManager.GetString("Common_FilePlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Files に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Common_Files {
            get {
                return ResourceManager.GetString("Common_Files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   file に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Common_FileSingular {
            get {
                return ResourceManager.GetString("Common_FileSingular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   folders に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Common_FolderPlural {
            get {
                return ResourceManager.GetString("Common_FolderPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Folders に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Common_Folders {
            get {
                return ResourceManager.GetString("Common_Folders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   folder に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Common_FolderSingular {
            get {
                return ResourceManager.GetString("Common_FolderSingular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Input history (Alt+Down / F4) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Common_History {
            get {
                return ResourceManager.GetString("Common_History", resourceCulture);
            }
        }
        
        /// <summary>
        ///   items に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Common_Items {
            get {
                return ResourceManager.GetString("Common_Items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Language に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Common_Language {
            get {
                return ResourceManager.GetString("Common_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   System language に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Common_LanguageAuto {
            get {
                return ResourceManager.GetString("Common_LanguageAuto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   简体中文 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Common_LanguageChineseSimplified {
            get {
                return ResourceManager.GetString("Common_LanguageChineseSimplified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   English に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Common_LanguageEnglish {
            get {
                return ResourceManager.GetString("Common_LanguageEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Add Languages\{culture}.txt beside the executable to supply a translation. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Common_LanguageHint {
            get {
                return ResourceManager.GetString("Common_LanguageHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   日本語 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Common_LanguageJapanese {
            get {
                return ResourceManager.GetString("Common_LanguageJapanese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   한국어 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Common_LanguageKorean {
            get {
                return ResourceManager.GetString("Common_LanguageKorean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The language will apply after DesktopIniManager restarts. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Common_LanguageRestart {
            get {
                return ResourceManager.GetString("Common_LanguageRestart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   LOCKED に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Common_Locked {
            get {
                return ResourceManager.GetString("Common_Locked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Name に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Common_Name {
            get {
                return ResourceManager.GetString("Common_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   OK に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Common_OK {
            get {
                return ResourceManager.GetString("Common_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please wait… に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Common_PleaseWait {
            get {
                return ResourceManager.GetString("Common_PleaseWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ready に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Common_Ready {
            get {
                return ResourceManager.GetString("Common_Ready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Search に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Common_Search {
            get {
                return ResourceManager.GetString("Common_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Common_Select {
            get {
                return ResourceManager.GetString("Common_Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Source に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Common_Source {
            get {
                return ResourceManager.GetString("Common_Source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   State に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Common_State {
            get {
                return ResourceManager.GetString("Common_State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sync に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Common_Sync {
            get {
                return ResourceManager.GetString("Common_Sync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Target に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Common_Target {
            get {
                return ResourceManager.GetString("Common_Target", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Type に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Common_Type {
            get {
                return ResourceManager.GetString("Common_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   100% に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Diff_ActualSize {
            get {
                return ResourceManager.GetString("Diff_ActualSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Binary and cache files are not supported in Diff View. Only text files and supported images can be displayed. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Diff_BinaryMessage {
            get {
                return ResourceManager.GetString("Diff_BinaryMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   This file type is not opened in Diff View. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Diff_BinaryRejected {
            get {
                return ResourceManager.GetString("Diff_BinaryRejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Fit に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Diff_Fit {
            get {
                return ResourceManager.GetString("Diff_Fit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Diff view に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Diff_Heading {
            get {
                return ResourceManager.GetString("Diff_Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hunk {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Diff_HunkN {
            get {
                return ResourceManager.GetString("Diff_HunkN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} hunks | left red = removed  right green = added | UTF-8 / BOM / Shift-JIS | large files use a simplified match に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Diff_HunkStatus {
            get {
                return ResourceManager.GetString("Diff_HunkStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Source: {0} | Target: {1} | shared zoom, top-left aligned (GIF/ICO first frame) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Diff_ImageStatus {
            get {
                return ResourceManager.GetString("Diff_ImageStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Loading… に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Diff_Loading {
            get {
                return ResourceManager.GetString("Diff_Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Missing に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Diff_Missing {
            get {
                return ResourceManager.GetString("Diff_Missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Next に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Diff_Next {
            get {
                return ResourceManager.GetString("Diff_Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   none に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Diff_None {
            get {
                return ResourceManager.GetString("Diff_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Open Source に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Diff_OpenSource {
            get {
                return ResourceManager.GetString("Diff_OpenSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Open Target に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Diff_OpenTarget {
            get {
                return ResourceManager.GetString("Diff_OpenTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} × {1} px に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Diff_Pixels {
            get {
                return ResourceManager.GetString("Diff_Pixels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Prev に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Diff_Prev {
            get {
                return ResourceManager.GetString("Diff_Prev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Source file does not exist. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Diff_SourceMissing {
            get {
                return ResourceManager.GetString("Diff_SourceMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Target file does not exist. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Diff_TargetMissing {
            get {
                return ResourceManager.GetString("Diff_TargetMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Diff View に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Diff_Title {
            get {
                return ResourceManager.GetString("Diff_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Diff view — {0} — read only に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Diff_TitleFile {
            get {
                return ResourceManager.GetString("Diff_TitleFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Files over 8 MB should be opened in an external editor. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Diff_TooLargeBytes {
            get {
                return ResourceManager.GetString("Diff_TooLargeBytes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Files over 100,000 lines should be opened in an external editor. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Diff_TooManyLines {
            get {
                return ResourceManager.GetString("Diff_TooManyLines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Unable to display: {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Diff_Unable {
            get {
                return ResourceManager.GetString("Diff_Unable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Visible range — drag to scroll に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Diff_VisibleRange {
            get {
                return ResourceManager.GetString("Diff_VisibleRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Zoom に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Diff_Zoom {
            get {
                return ResourceManager.GetString("Diff_Zoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Shared zoom for Source and Target に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Diff_ZoomShared {
            get {
                return ResourceManager.GetString("Diff_ZoomShared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Access was denied. Check file permissions and read-only attributes. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Err_AccessDenied {
            get {
                return ResourceManager.GetString("Err_AccessDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The folder or part of the path could not be found. Check Source and Target, then compare again. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Err_DirectoryNotFound {
            get {
                return ResourceManager.GetString("Err_DirectoryNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The drive could not be found or is unavailable. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Err_DriveNotFound {
            get {
                return ResourceManager.GetString("Err_DriveNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   File: {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Err_FileLabel {
            get {
                return ResourceManager.GetString("Err_FileLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The file is locked by another process. Close the application using it and try again. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Err_FileLocked {
            get {
                return ResourceManager.GetString("Err_FileLocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The file could not be found. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Err_FileNotFound {
            get {
                return ResourceManager.GetString("Err_FileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The operation could not be completed. Error code: 0x{0} ({1}). に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Err_Generic {
            get {
                return ResourceManager.GetString("Err_Generic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The file or folder path is too long. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Err_PathTooLong {
            get {
                return ResourceManager.GetString("Err_PathTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Browse editor に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Grep_BrowseEditor {
            get {
                return ResourceManager.GetString("Grep_BrowseEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cancel the current search before changing scopes に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Grep_CancelBeforeChange {
            get {
                return ResourceManager.GetString("Grep_CancelBeforeChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cancelling… に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Grep_Cancelling {
            get {
                return ResourceManager.GetString("Grep_Cancelling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Column に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Grep_Column {
            get {
                return ResourceManager.GetString("Grep_Column", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Editor に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Grep_Editor {
            get {
                return ResourceManager.GetString("Grep_Editor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Arguments ({file}, {line}, {column}) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Grep_EditorArguments {
            get {
                return ResourceManager.GetString("Grep_EditorArguments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Editor executable or command に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Grep_EditorExecutable {
            get {
                return ResourceManager.GetString("Grep_EditorExecutable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Could not open the editor.
        ///
        ///{0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Grep_EditorFailed {
            get {
                return ResourceManager.GetString("Grep_EditorFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Applications|*.exe|All files|*.* に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Grep_EditorFilter {
            get {
                return ResourceManager.GetString("Grep_EditorFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Enter one or more file extensions for the Free profile. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Grep_EnterExtensions {
            get {
                return ResourceManager.GetString("Grep_EnterExtensions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Enter search text. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Grep_EnterText {
            get {
                return ResourceManager.GetString("Grep_EnterText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   File name に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Grep_FileName {
            get {
                return ResourceManager.GetString("Grep_FileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} folders に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Grep_FolderPlural {
            get {
                return ResourceManager.GetString("Grep_FolderPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} folder に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Grep_FolderSingular {
            get {
                return ResourceManager.GetString("Grep_FolderSingular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Included extensions に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Grep_IncludedExtensions {
            get {
                return ResourceManager.GetString("Grep_IncludedExtensions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The search expression is invalid.
        ///
        ///{0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Grep_InvalidExpression {
            get {
                return ResourceManager.GetString("Grep_InvalidExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Invalid expression に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Grep_InvalidExpressionStatus {
            get {
                return ResourceManager.GetString("Grep_InvalidExpressionStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Language profile に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Grep_LanguageProfile {
            get {
                return ResourceManager.GetString("Grep_LanguageProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Line に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Grep_Line {
            get {
                return ResourceManager.GetString("Grep_Line", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Match に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Grep_Match {
            get {
                return ResourceManager.GetString("Grep_Match", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Match case に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Grep_MatchCase {
            get {
                return ResourceManager.GetString("Grep_MatchCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No folders selected に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Grep_NoFoldersSelected {
            get {
                return ResourceManager.GetString("Grep_NoFoldersSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Project に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Grep_Project {
            get {
                return ResourceManager.GetString("Grep_Project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Regular expression に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Grep_Regex {
            get {
                return ResourceManager.GetString("Grep_Regex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Reload に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Grep_Reload {
            get {
                return ResourceManager.GetString("Grep_Reload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Reload selection に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Grep_ReloadSelection {
            get {
                return ResourceManager.GetString("Grep_ReloadSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} matches in {1} files に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Grep_Result {
            get {
                return ResourceManager.GetString("Grep_Result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} matches in {1} files · {2} skipped に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Grep_ResultSkipped {
            get {
                return ResourceManager.GetString("Grep_ResultSkipped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Search only the projects selected in DesktopIniManager に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Grep_ScopeHint {
            get {
                return ResourceManager.GetString("Grep_ScopeHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Search cancelled に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Grep_SearchCancelled {
            get {
                return ResourceManager.GetString("Grep_SearchCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Search failed に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Grep_SearchFailed {
            get {
                return ResourceManager.GetString("Grep_SearchFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Searching {0} / {1} files… に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Grep_SearchingFiles {
            get {
                return ResourceManager.GetString("Grep_SearchingFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Search text に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Grep_SearchText {
            get {
                return ResourceManager.GetString("Grep_SearchText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select one or more project folders in DesktopIniManager. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Grep_SelectFolders {
            get {
                return ResourceManager.GetString("Grep_SelectFolders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Scoped Code Grep に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Grep_Title {
            get {
                return ResourceManager.GetString("Grep_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Whole word に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Grep_WholeWord {
            get {
                return ResourceManager.GetString("Grep_WholeWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Double-click an icon to select it に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Icon_Hint {
            get {
                return ResourceManager.GetString("Icon_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} icons に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Icon_NIcons {
            get {
                return ResourceManager.GetString("Icon_NIcons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Choose Icon に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Icon_Title {
            get {
                return ResourceManager.GetString("Icon_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Add desktop.ini to .gitignore に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Main_AddGitignore {
            get {
                return ResourceManager.GetString("Main_AddGitignore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Applied to {0} folders に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Main_AppliedTo {
            get {
                return ResourceManager.GetString("Main_AppliedTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Icon settings applied. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Main_ApplyOk {
            get {
                return ResourceManager.GetString("Main_ApplyOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Icon settings applied.
        ///{0} succeeded, {1} failed に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Main_ApplyResult {
            get {
                return ResourceManager.GetString("Main_ApplyResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Apply to selected folders に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Main_ApplyTooltip {
            get {
                return ResourceManager.GetString("Main_ApplyTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Building {0} folder rows… に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Main_BuildingRows {
            get {
                return ResourceManager.GetString("Main_BuildingRows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Building folder tree… に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Main_BuildingTree {
            get {
                return ResourceManager.GetString("Main_BuildingTree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Change library に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Main_ChangeLibrary {
            get {
                return ResourceManager.GetString("Main_ChangeLibrary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Choose icon に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Main_ChooseIcon {
            get {
                return ResourceManager.GetString("Main_ChooseIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Choose an icon library first. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Main_ChooseLibraryFirst {
            get {
                return ResourceManager.GetString("Main_ChooseLibraryFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cloud and network locations are not supported. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Main_CloudUnsupported {
            get {
                return ResourceManager.GetString("Main_CloudUnsupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Apply the selected icon to {0} folders? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Main_ConfirmApply {
            get {
                return ResourceManager.GetString("Main_ConfirmApply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Delete desktop.ini and remove icon settings from {0} folders? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Main_ConfirmRemove {
            get {
                return ResourceManager.GetString("Main_ConfirmRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The drive index could not be read. Using standard search… に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Main_DriveIndexFailed {
            get {
                return ResourceManager.GetString("Main_DriveIndexFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Administrator permission was cancelled に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Main_ElevationCancelled {
            get {
                return ResourceManager.GetString("Main_ElevationCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Could not restart with administrator permission. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Main_ElevationFailed {
            get {
                return ResourceManager.GetString("Main_ElevationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Windows may ask for permission に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Main_ElevationHint {
            get {
                return ResourceManager.GetString("Main_ElevationHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Could not open the folder in Explorer. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Main_ExplorerFailed {
            get {
                return ResourceManager.GetString("Main_ExplorerFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Use fast NTFS search に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Main_FastNtfs {
            get {
                return ResourceManager.GetString("Main_FastNtfs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Fast NTFS search permission was unavailable. Using standard search… に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Main_FastPermissionUnavailable {
            get {
                return ResourceManager.GetString("Main_FastPermissionUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Fast NTFS search is unavailable here. Using standard search… に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Main_FastUnavailable {
            get {
                return ResourceManager.GetString("Main_FastUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Files — {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Main_FilesHeader {
            get {
                return ResourceManager.GetString("Main_FilesHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Filter folders に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Main_FilterFolders {
            get {
                return ResourceManager.GetString("Main_FilterFolders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Space-separated words; all words must match the folder path に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Main_FilterTooltip {
            get {
                return ResourceManager.GetString("Main_FilterTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Could not open the folder picker. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Main_FolderPickerFailed {
            get {
                return ResourceManager.GetString("Main_FolderPickerFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} folders found · analyzing projects… に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Main_FoldersAnalyzing {
            get {
                return ResourceManager.GetString("Main_FoldersAnalyzing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} folders found に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Main_FoldersFound {
            get {
                return ResourceManager.GetString("Main_FoldersFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   GIT に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Main_Git {
            get {
                return ResourceManager.GetString("Main_Git", resourceCulture);
            }
        }
        
        /// <summary>
        ///   GIT Search に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Main_GitSearch {
            get {
                return ResourceManager.GetString("Main_GitSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Scoped Code Grep に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Main_Grep {
            get {
                return ResourceManager.GetString("Main_Grep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Grep this folder に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Main_GrepThisFolder {
            get {
                return ResourceManager.GetString("Main_GrepThisFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Grep selected folders に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Main_GrepTooltip {
            get {
                return ResourceManager.GetString("Main_GrepTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hide unchecked folders に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Main_HideUnchecked {
            get {
                return ResourceManager.GetString("Main_HideUnchecked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Icon に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Main_Icon {
            get {
                return ResourceManager.GetString("Main_Icon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Icon Apply に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Main_IconApply {
            get {
                return ResourceManager.GetString("Main_IconApply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Could not open the icon browser. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Main_IconBrowserFailed {
            get {
                return ResourceManager.GetString("Main_IconBrowserFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Icon selection cancelled に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Main_IconCancelled {
            get {
                return ResourceManager.GetString("Main_IconCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Icon resources|*.ico;*.icl;*.dll;*.exe|All files|*.* に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Main_IconFilter {
            get {
                return ResourceManager.GetString("Main_IconFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ICO / ICL / DLL / EXE に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Main_IconFormats {
            get {
                return ResourceManager.GetString("Main_IconFormats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Icon {0} selected に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Main_IconNSelected {
            get {
                return ResourceManager.GetString("Main_IconNSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Icon Remove に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Main_IconRemove {
            get {
                return ResourceManager.GetString("Main_IconRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Indexed {0} folders に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Main_IndexedFolders {
            get {
                return ResourceManager.GetString("Main_IndexedFolders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Indexed {0} folders… に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Main_IndexedFoldersEllipsis {
            get {
                return ResourceManager.GetString("Main_IndexedFoldersEllipsis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Index {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Main_IndexN {
            get {
                return ResourceManager.GetString("Main_IndexN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Invert に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Main_Invert {
            get {
                return ResourceManager.GetString("Main_Invert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Invert selection に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Main_InvertSelection {
            get {
                return ResourceManager.GetString("Main_InvertSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Keywords (optional) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Main_KeywordsOptional {
            get {
                return ResourceManager.GetString("Main_KeywordsOptional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Large icons に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Main_LargeIcons {
            get {
                return ResourceManager.GetString("Main_LargeIcons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Library に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Main_Library {
            get {
                return ResourceManager.GetString("Main_Library", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Could not select the icon library. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Main_LibrarySelectFailed {
            get {
                return ResourceManager.GetString("Main_LibrarySelectFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   List に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Main_List {
            get {
                return ResourceManager.GetString("Main_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Loading icons… に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Main_LoadingIcons {
            get {
                return ResourceManager.GetString("Main_LoadingIcons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The search location does not exist. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Main_LocationMissing {
            get {
                return ResourceManager.GetString("Main_LocationMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Search location set to {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Main_LocationSet {
            get {
                return ResourceManager.GetString("Main_LocationSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} matches found · analyzing projects… に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Main_MatchesAnalyzing {
            get {
                return ResourceManager.GetString("Main_MatchesAnalyzing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Developer Differencer に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Main_Mft {
            get {
                return ResourceManager.GetString("Main_Mft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Compare and synchronize folders に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Main_MftTooltip {
            get {
                return ResourceManager.GetString("Main_MftTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} folders に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Main_NFolders {
            get {
                return ResourceManager.GetString("Main_NFolders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} items に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Main_NItems {
            get {
                return ResourceManager.GetString("Main_NItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} matches に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Main_NMatches {
            get {
                return ResourceManager.GetString("Main_NMatches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No folders are available for Grep. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Main_NoGrepFolders {
            get {
                return ResourceManager.GetString("Main_NoGrepFolders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No icon groups were found. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Main_NoIconGroups {
            get {
                return ResourceManager.GetString("Main_NoIconGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Not selected に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Main_NotSelected {
            get {
                return ResourceManager.GetString("Main_NotSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Could not open the file. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Main_OpenFileFailed {
            get {
                return ResourceManager.GetString("Main_OpenFileFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Open in Explorer に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Main_OpenInExplorer {
            get {
                return ResourceManager.GetString("Main_OpenInExplorer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Physical に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Main_Physical {
            get {
                return ResourceManager.GetString("Main_Physical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Preview unavailable に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Main_PreviewUnavailable {
            get {
                return ResourceManager.GetString("Main_PreviewUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Reading the NTFS index… に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Main_ReadingNtfs {
            get {
                return ResourceManager.GetString("Main_ReadingNtfs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Removed settings from {0} folders に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Main_RemovedFrom {
            get {
                return ResourceManager.GetString("Main_RemovedFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Icon settings removed. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Main_RemoveOk {
            get {
                return ResourceManager.GetString("Main_RemoveOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Icon settings removed.
        ///{0} succeeded, {1} failed に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Main_RemoveResult {
            get {
                return ResourceManager.GetString("Main_RemoveResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Remove settings に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Main_RemoveSettings {
            get {
                return ResourceManager.GetString("Main_RemoveSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Replacement icon に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Main_ReplacementIcon {
            get {
                return ResourceManager.GetString("Main_ReplacementIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed to restore folder trees: {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Main_RestoreTreesFailed {
            get {
                return ResourceManager.GetString("Main_RestoreTreesFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed to save folder trees: {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Main_SaveTreesFailed {
            get {
                return ResourceManager.GetString("Main_SaveTreesFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Scanning {0} folders… に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Main_ScanningFolders {
            get {
                return ResourceManager.GetString("Main_ScanningFolders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Search cancelled に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Main_SearchCancelled {
            get {
                return ResourceManager.GetString("Main_SearchCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Search failed に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Main_SearchFailed {
            get {
                return ResourceManager.GetString("Main_SearchFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Search location に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Main_SearchLocation {
            get {
                return ResourceManager.GetString("Main_SearchLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} search results に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Main_SearchResults {
            get {
                return ResourceManager.GetString("Main_SearchResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Selected icon に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Main_SelectedIcon {
            get {
                return ResourceManager.GetString("Main_SelectedIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///    selected に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Main_SelectedSuffix {
            get {
                return ResourceManager.GetString("Main_SelectedSuffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select at least one folder. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Main_SelectOneFolder {
            get {
                return ResourceManager.GetString("Main_SelectOneFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select a search folder に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Main_SelectSearchFolder {
            get {
                return ResourceManager.GetString("Main_SelectSearchFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Show hidden folders に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Main_ShowHidden {
            get {
                return ResourceManager.GetString("Main_ShowHidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Small icons に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Main_SmallIcons {
            get {
                return ResourceManager.GetString("Main_SmallIcons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Solution に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Main_Solution {
            get {
                return ResourceManager.GetString("Main_Solution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} solutions found に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Main_SolutionsFound {
            get {
                return ResourceManager.GetString("Main_SolutionsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Find folders by name or content and apply custom icons in batches に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Main_Subtitle {
            get {
                return ResourceManager.GetString("Main_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Comfortable folder list に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Main_TreeComfortable {
            get {
                return ResourceManager.GetString("Main_TreeComfortable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Compact folder list に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Main_TreeCompact {
            get {
                return ResourceManager.GetString("Main_TreeCompact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Folder trees restored. Use Git to refresh. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Main_TreesRestored {
            get {
                return ResourceManager.GetString("Main_TreesRestored", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Use as search location に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Main_UseAsSearchLocation {
            get {
                return ResourceManager.GetString("Main_UseAsSearchLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   0 matches に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Main_ZeroMatches {
            get {
                return ResourceManager.GetString("Main_ZeroMatches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   All folders に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Mft_AllFolders {
            get {
                return ResourceManager.GetString("Mft_AllFolders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} bytes に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Mft_Bytes {
            get {
                return ResourceManager.GetString("Mft_Bytes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cancel comparison に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Mft_CancelCompare {
            get {
                return ResourceManager.GetString("Mft_CancelCompare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cancelling comparison… に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Mft_CancellingCompare {
            get {
                return ResourceManager.GetString("Mft_CancellingCompare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Changed after compare. Compare again. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Mft_ChangedAfterCompare {
            get {
                return ResourceManager.GetString("Mft_ChangedAfterCompare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Changed during copy. Compare again. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Mft_ChangedDuringCopy {
            get {
                return ResourceManager.GetString("Mft_ChangedDuringCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Choose a local root outside .git. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Mft_ChooseLocalRoot {
            get {
                return ResourceManager.GetString("Mft_ChooseLocalRoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Classifying differences by relative path… に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Mft_Classifying {
            get {
                return ResourceManager.GetString("Mft_Classifying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Clean cancelled. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Mft_CleanCancelled {
            get {
                return ResourceManager.GetString("Mft_CleanCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Clean complete: {0} succeeded / {1} failed. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Mft_CleanComplete {
            get {
                return ResourceManager.GetString("Mft_CleanComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select solutions to clean with MSBuild. The list will be compared again after cleaning.
        ///Solutions containing this running DIM are disabled. To clean them, start DIM from a separate release folder outside the solution. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Mft_CleanDialogHint {
            get {
                return ResourceManager.GetString("Mft_CleanDialogHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Clean failed: {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Mft_CleanFailed {
            get {
                return ResourceManager.GetString("Mft_CleanFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cleaning {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Mft_Cleaning {
            get {
                return ResourceManager.GetString("Mft_Cleaning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Clean solution に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Mft_CleanSolution {
            get {
                return ResourceManager.GetString("Mft_CleanSolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Clean solutions に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Mft_CleanSolutionsTitle {
            get {
                return ResourceManager.GetString("Mft_CleanSolutionsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Choose solutions and configurations to clean with MSBuild, then compare again に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Mft_CleanTip {
            get {
                return ResourceManager.GetString("Mft_CleanTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Compare cancelled に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Mft_CompareCancelled {
            get {
                return ResourceManager.GetString("Mft_CompareCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Compare dates に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Mft_CompareDates {
            get {
                return ResourceManager.GetString("Mft_CompareDates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Include last-write timestamps when classifying differences に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Mft_CompareDatesTip {
            get {
                return ResourceManager.GetString("Mft_CompareDatesTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Compare failed (sync disabled): {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Mft_CompareFailed {
            get {
                return ResourceManager.GetString("Mft_CompareFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Complete  OK {0} / FAIL {1} / LOCKED {2} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Mft_CompleteCounts {
            get {
                return ResourceManager.GetString("Mft_CompleteCounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Configurations (semicolon separated; solution default platform) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Mft_ConfigurationsLabel {
            get {
                return ResourceManager.GetString("Mft_ConfigurationsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} differences / {1} identical. Check items to synchronize. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Mft_DifferencesSummary {
            get {
                return ResourceManager.GetString("Mft_DifferencesSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Present on both sides with different timestamp or size に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Mft_DifferentMeta {
            get {
                return ResourceManager.GetString("Mft_DifferentMeta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Diff View に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Mft_DiffView {
            get {
                return ResourceManager.GetString("Mft_DiffView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Contains the running DIM; start DIM from a separate release folder to clean this solution. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Mft_DimLockedTip {
            get {
                return ResourceManager.GetString("Mft_DimLockedTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Enumerating MFT and comparing timestamps and sizes… に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Mft_Enumerating {
            get {
                return ResourceManager.GetString("Mft_Enumerating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   FAIL (exit {0}) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Mft_FailExit {
            get {
                return ResourceManager.GetString("Mft_FailExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   FAIL {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Mft_FailPrefix {
            get {
                return ResourceManager.GetString("Mft_FailPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   A file disappeared during compare. Compare again: {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Mft_FileDisappeared {
            get {
                return ResourceManager.GetString("Mft_FileDisappeared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Files — all levels に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Mft_FilesAllLevels {
            get {
                return ResourceManager.GetString("Mft_FilesAllLevels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} differences / {1} identical (OBJ/BIN filters applied). Check items to synchronize. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Mft_FilterSummary {
            get {
                return ResourceManager.GetString("Mft_FilterSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Finding solutions… に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Mft_FindingSolutions {
            get {
                return ResourceManager.GetString("Mft_FindingSolutions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hard links are excluded: {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Mft_HardLinkExcluded {
            get {
                return ResourceManager.GetString("Mft_HardLinkExcluded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Links and junctions are excluded: {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Mft_LinkExcluded {
            get {
                return ResourceManager.GetString("Mft_LinkExcluded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   LOCKED {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Mft_LockedPrefix {
            get {
                return ResourceManager.GetString("Mft_LockedPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Log: {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Mft_LogLabel {
            get {
                return ResourceManager.GetString("Mft_LogLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   MFT unavailable for {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Mft_MftUnavailableFor {
            get {
                return ResourceManager.GetString("Mft_MftUnavailableFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Choose Source and Target, then Compare. Local NTFS and an elevated DIM process are required. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Mft_NeedRoots {
            get {
                return ResourceManager.GetString("Mft_NeedRoots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No solutions found under Source or Target. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Mft_NoSolutions {
            get {
                return ResourceManager.GetString("Mft_NoSolutions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   (not compared) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Mft_NotCompared {
            get {
                return ResourceManager.GetString("Mft_NotCompared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Not a regular file: {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Mft_NotRegularFile {
            get {
                return ResourceManager.GetString("Mft_NotRegularFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   OK {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Mft_OkPrefix {
            get {
                return ResourceManager.GetString("Mft_OkPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Existing files may be overwritten or removed. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Mft_OverwriteWarning {
            get {
                return ResourceManager.GetString("Mft_OverwriteWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Preview unavailable: {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Mft_PreviewUnavailable {
            get {
                return ResourceManager.GetString("Mft_PreviewUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} — {1} / {2} items に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Mft_ProgressItems {
            get {
                return ResourceManager.GetString("Mft_ProgressItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Protected or invalid relative path: {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Mft_ProtectedPath {
            get {
                return ResourceManager.GetString("Mft_ProtectedPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Reading timestamps and sizes… に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Mft_ReadingMeta {
            get {
                return ResourceManager.GetString("Mft_ReadingMeta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Reading MFT for {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Mft_ReadingMftFor {
            get {
                return ResourceManager.GetString("Mft_ReadingMftFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Refused a path outside the root or inside .git. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Mft_RefusedPath {
            get {
                return ResourceManager.GetString("Mft_RefusedPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Source and Target restored. Click Compare to build the difference tree. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Mft_RestoredClickCompare {
            get {
                return ResourceManager.GetString("Mft_RestoredClickCompare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed to restore tree: {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Mft_RestoreTreeFailed {
            get {
                return ResourceManager.GetString("Mft_RestoreTreeFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Roots must not be equal or nested. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Mft_RootsNested {
            get {
                return ResourceManager.GetString("Mft_RootsNested", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Same timestamp and size に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Mft_SameTimeSize {
            get {
                return ResourceManager.GetString("Mft_SameTimeSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed to save log: {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Mft_SaveLogFailed {
            get {
                return ResourceManager.GetString("Mft_SaveLogFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed to save tree: {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Mft_SaveTreeFailed {
            get {
                return ResourceManager.GetString("Mft_SaveTreeFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   File-system scan complete. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Mft_ScanComplete {
            get {
                return ResourceManager.GetString("Mft_ScanComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Scanning files without MFT… に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Mft_ScanWithoutMft {
            get {
                return ResourceManager.GetString("Mft_ScanWithoutMft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Selected に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Mft_Selected {
            get {
                return ResourceManager.GetString("Mft_Selected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Selected {0} (includes {1} hidden) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Mft_SelectedIncludesHidden {
            get {
                return ResourceManager.GetString("Mft_SelectedIncludesHidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select at least one solution and enter configuration names such as Debug;Release. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Mft_SelectSolutions {
            get {
                return ResourceManager.GetString("Mft_SelectSolutions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Show bin folders and their files に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Mft_ShowBin {
            get {
                return ResourceManager.GetString("Mft_ShowBin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Show obj folders and their files に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Mft_ShowObj {
            get {
                return ResourceManager.GetString("Mft_ShowObj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SKIP same {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Mft_SkipSame {
            get {
                return ResourceManager.GetString("Mft_SkipSame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Source folder に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Mft_SourceFolder {
            get {
                return ResourceManager.GetString("Mft_SourceFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Source: {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Mft_SourceLabel {
            get {
                return ResourceManager.GetString("Mft_SourceLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Source (left) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Mft_SourceLeft {
            get {
                return ResourceManager.GetString("Mft_SourceLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Present on Source only に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Mft_SourceOnly {
            get {
                return ResourceManager.GetString("Mft_SourceOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Source to Target に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Mft_SourceToTarget {
            get {
                return ResourceManager.GetString("Mft_SourceToTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   NEW に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Mft_StateNew {
            get {
                return ResourceManager.GetString("Mft_StateNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   OLD に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Mft_StateOld {
            get {
                return ResourceManager.GetString("Mft_StateOld", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Same に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Mft_StateSame {
            get {
                return ResourceManager.GetString("Mft_StateSame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Size differs に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Mft_StateSizeDiffers {
            get {
                return ResourceManager.GetString("Mft_StateSizeDiffers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Source only に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Mft_StateSourceOnly {
            get {
                return ResourceManager.GetString("Mft_StateSourceOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Target only に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Mft_StateTargetOnly {
            get {
                return ResourceManager.GetString("Mft_StateTargetOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Time / size differs に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Mft_StateTimeSizeDiffers {
            get {
                return ResourceManager.GetString("Mft_StateTimeSizeDiffers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Synchronize に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Mft_Synchronize {
            get {
                return ResourceManager.GetString("Mft_Synchronize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Synchronizing — {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Mft_Synchronizing {
            get {
                return ResourceManager.GetString("Mft_Synchronizing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} — syncing… に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Mft_Syncing {
            get {
                return ResourceManager.GetString("Mft_Syncing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sync result — OK {0} / FAIL {1} / LOCKED {2} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Mft_SyncResultTitle {
            get {
                return ResourceManager.GetString("Mft_SyncResultTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Synchronize selected files に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Mft_SyncSelectedTitle {
            get {
                return ResourceManager.GetString("Mft_SyncSelectedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Synchronize files に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Mft_SyncTitle {
            get {
                return ResourceManager.GetString("Mft_SyncTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Target folder に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Mft_TargetFolder {
            get {
                return ResourceManager.GetString("Mft_TargetFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Target: {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Mft_TargetLabel {
            get {
                return ResourceManager.GetString("Mft_TargetLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Present on Target only に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Mft_TargetOnly {
            get {
                return ResourceManager.GetString("Mft_TargetOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Target (right) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Mft_TargetRight {
            get {
                return ResourceManager.GetString("Mft_TargetRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Target to Source に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Mft_TargetToSource {
            get {
                return ResourceManager.GetString("Mft_TargetToSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Developer Differencer に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Mft_Title {
            get {
                return ResourceManager.GetString("Mft_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Updating the difference tree… に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Mft_UpdatingTree {
            get {
                return ResourceManager.GetString("Mft_UpdatingTree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Synchronization verification failed: destination timestamp, size or existence differs. Compare again. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Mft_VerifyFailed {
            get {
                return ResourceManager.GetString("Mft_VerifyFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   By Tamayan に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Splash_Author {
            get {
                return ResourceManager.GetString("Splash_Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Building the workspace… に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Splash_BuildingWorkspace {
            get {
                return ResourceManager.GetString("Splash_BuildingWorkspace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   © {0} ZEBRASOFT Co.,Ltd. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Splash_Copyright {
            get {
                return ResourceManager.GetString("Splash_Copyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Initializing… に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Splash_Initializing {
            get {
                return ResourceManager.GetString("Splash_Initializing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Loading startup settings… に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Splash_LoadingSettings {
            get {
                return ResourceManager.GetString("Splash_LoadingSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Preparing folder icons… に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Splash_PreparingIcons {
            get {
                return ResourceManager.GetString("Splash_PreparingIcons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ready に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Splash_Ready {
            get {
                return ResourceManager.GetString("Splash_Ready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Restoring saved folder trees… に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Splash_RestoringTrees {
            get {
                return ResourceManager.GetString("Splash_RestoringTrees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DesktopIniManager — Starting に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Splash_Title {
            get {
                return ResourceManager.GetString("Splash_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Dark mode に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Theme_Dark {
            get {
                return ResourceManager.GetString("Theme_Dark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Light mode に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Theme_Light {
            get {
                return ResourceManager.GetString("Theme_Light", resourceCulture);
            }
        }
    }
}
