//------------------------------------------------------------------------------
// <auto-generated>
//     Strongly-typed resources.
// </auto-generated>
//------------------------------------------------------------------------------
namespace DesktopIniManager.Properties {
    using System;
    public class Strings {
        public static string Common_History {
            get { return StringOverlay.Get("Common_History"); }
        }
        private static System.Resources.ResourceManager resourceMan;
        private static System.Globalization.CultureInfo resourceCulture;
        internal Strings() {}
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    resourceMan = new System.Resources.ResourceManager("DesktopIniManager.Properties.Strings", typeof(Strings).Assembly);
                }
                return resourceMan;
            }
        }
        public static System.Globalization.CultureInfo Culture {
            get { return resourceCulture; }
            set { resourceCulture = value; }
        }
        public static string App_Title {
            get { return StringOverlay.Get("App_Title"); }
        }
        public static string App_ProductName {
            get { return StringOverlay.Get("App_ProductName"); }
        }
        public static string App_StartFailed {
            get { return StringOverlay.Get("App_StartFailed"); }
        }
        public static string App_Unhandled {
            get { return StringOverlay.Get("App_Unhandled"); }
        }
        public static string Splash_Title {
            get { return StringOverlay.Get("Splash_Title"); }
        }
        public static string Splash_Initializing {
            get { return StringOverlay.Get("Splash_Initializing"); }
        }
        public static string Splash_LoadingSettings {
            get { return StringOverlay.Get("Splash_LoadingSettings"); }
        }
        public static string Splash_RestoringTrees {
            get { return StringOverlay.Get("Splash_RestoringTrees"); }
        }
        public static string Splash_PreparingIcons {
            get { return StringOverlay.Get("Splash_PreparingIcons"); }
        }
        public static string Splash_BuildingWorkspace {
            get { return StringOverlay.Get("Splash_BuildingWorkspace"); }
        }
        public static string Splash_Ready {
            get { return StringOverlay.Get("Splash_Ready"); }
        }
        public static string Splash_Copyright {
            get { return StringOverlay.Get("Splash_Copyright"); }
        }
        public static string Splash_Author {
            get { return StringOverlay.Get("Splash_Author"); }
        }
        public static string Common_Close {
            get { return StringOverlay.Get("Common_Close"); }
        }
        public static string Common_Cancel {
            get { return StringOverlay.Get("Common_Cancel"); }
        }
        public static string Common_Browse {
            get { return StringOverlay.Get("Common_Browse"); }
        }
        public static string Common_Search {
            get { return StringOverlay.Get("Common_Search"); }
        }
        public static string Common_Clear {
            get { return StringOverlay.Get("Common_Clear"); }
        }
        public static string Common_Ready {
            get { return StringOverlay.Get("Common_Ready"); }
        }
        public static string Common_PleaseWait {
            get { return StringOverlay.Get("Common_PleaseWait"); }
        }
        public static string Common_Expand {
            get { return StringOverlay.Get("Common_Expand"); }
        }
        public static string Common_Collapse {
            get { return StringOverlay.Get("Common_Collapse"); }
        }
        public static string Common_Name {
            get { return StringOverlay.Get("Common_Name"); }
        }
        public static string Common_Type {
            get { return StringOverlay.Get("Common_Type"); }
        }
        public static string Common_State {
            get { return StringOverlay.Get("Common_State"); }
        }
        public static string Common_Files {
            get { return StringOverlay.Get("Common_Files"); }
        }
        public static string Common_Folders {
            get { return StringOverlay.Get("Common_Folders"); }
        }
        public static string Common_Source {
            get { return StringOverlay.Get("Common_Source"); }
        }
        public static string Common_Target {
            get { return StringOverlay.Get("Common_Target"); }
        }
        public static string Common_Select {
            get { return StringOverlay.Get("Common_Select"); }
        }
        public static string Common_Compare {
            get { return StringOverlay.Get("Common_Compare"); }
        }
        public static string Common_Clean {
            get { return StringOverlay.Get("Common_Clean"); }
        }
        public static string Common_Sync {
            get { return StringOverlay.Get("Common_Sync"); }
        }
        public static string Common_OK {
            get { return StringOverlay.Get("Common_OK"); }
        }
        public static string Common_Fail {
            get { return StringOverlay.Get("Common_Fail"); }
        }
        public static string Common_Locked {
            get { return StringOverlay.Get("Common_Locked"); }
        }
        public static string Common_Items {
            get { return StringOverlay.Get("Common_Items"); }
        }
        public static string Common_FileSingular {
            get { return StringOverlay.Get("Common_FileSingular"); }
        }
        public static string Common_FilePlural {
            get { return StringOverlay.Get("Common_FilePlural"); }
        }
        public static string Common_FolderSingular {
            get { return StringOverlay.Get("Common_FolderSingular"); }
        }
        public static string Common_FolderPlural {
            get { return StringOverlay.Get("Common_FolderPlural"); }
        }
        public static string Common_Language {
            get { return StringOverlay.Get("Common_Language"); }
        }
        public static string Common_LanguageAuto {
            get { return StringOverlay.Get("Common_LanguageAuto"); }
        }
        public static string Common_LanguageEnglish {
            get { return StringOverlay.Get("Common_LanguageEnglish"); }
        }
        public static string Common_LanguageJapanese {
            get { return StringOverlay.Get("Common_LanguageJapanese"); }
        }
        public static string Common_LanguageChineseSimplified {
            get { return StringOverlay.Get("Common_LanguageChineseSimplified"); }
        }
        public static string Common_LanguageKorean {
            get { return StringOverlay.Get("Common_LanguageKorean"); }
        }
        public static string Common_LanguageRestart {
            get { return StringOverlay.Get("Common_LanguageRestart"); }
        }
        public static string Common_LanguageHint {
            get { return StringOverlay.Get("Common_LanguageHint"); }
        }
        public static string Theme_Light {
            get { return StringOverlay.Get("Theme_Light"); }
        }
        public static string Theme_Dark {
            get { return StringOverlay.Get("Theme_Dark"); }
        }
        public static string Main_Subtitle {
            get { return StringOverlay.Get("Main_Subtitle"); }
        }
        public static string Main_FastNtfs {
            get { return StringOverlay.Get("Main_FastNtfs"); }
        }
        public static string Main_ElevationHint {
            get { return StringOverlay.Get("Main_ElevationHint"); }
        }
        public static string Main_SearchLocation {
            get { return StringOverlay.Get("Main_SearchLocation"); }
        }
        public static string Main_CloudUnsupported {
            get { return StringOverlay.Get("Main_CloudUnsupported"); }
        }
        public static string Main_KeywordsOptional {
            get { return StringOverlay.Get("Main_KeywordsOptional"); }
        }
        public static string Main_GitSearch {
            get { return StringOverlay.Get("Main_GitSearch"); }
        }
        public static string Main_Git {
            get { return StringOverlay.Get("Main_Git"); }
        }
        public static string Main_ReplacementIcon {
            get { return StringOverlay.Get("Main_ReplacementIcon"); }
        }
        public static string Main_IconFormats {
            get { return StringOverlay.Get("Main_IconFormats"); }
        }
        public static string Main_ChangeLibrary {
            get { return StringOverlay.Get("Main_ChangeLibrary"); }
        }
        public static string Main_Library {
            get { return StringOverlay.Get("Main_Library"); }
        }
        public static string Main_ChooseIcon {
            get { return StringOverlay.Get("Main_ChooseIcon"); }
        }
        public static string Main_Icon {
            get { return StringOverlay.Get("Main_Icon"); }
        }
        public static string Main_SelectedIcon {
            get { return StringOverlay.Get("Main_SelectedIcon"); }
        }
        public static string Main_NotSelected {
            get { return StringOverlay.Get("Main_NotSelected"); }
        }
        public static string Main_InvertSelection {
            get { return StringOverlay.Get("Main_InvertSelection"); }
        }
        public static string Main_Invert {
            get { return StringOverlay.Get("Main_Invert"); }
        }
        public static string Main_HideUnchecked {
            get { return StringOverlay.Get("Main_HideUnchecked"); }
        }
        public static string Main_ShowHidden {
            get { return StringOverlay.Get("Main_ShowHidden"); }
        }
        public static string Main_TreeCompact {
            get { return StringOverlay.Get("Main_TreeCompact"); }
        }
        public static string Main_TreeComfortable {
            get { return StringOverlay.Get("Main_TreeComfortable"); }
        }
        public static string Main_AddGitignore {
            get { return StringOverlay.Get("Main_AddGitignore"); }
        }
        public static string Main_ZeroMatches {
            get { return StringOverlay.Get("Main_ZeroMatches"); }
        }
        public static string Main_FilterFolders {
            get { return StringOverlay.Get("Main_FilterFolders"); }
        }
        public static string Main_FilterTooltip {
            get { return StringOverlay.Get("Main_FilterTooltip"); }
        }
        public static string Main_UseAsSearchLocation {
            get { return StringOverlay.Get("Main_UseAsSearchLocation"); }
        }
        public static string Main_OpenInExplorer {
            get { return StringOverlay.Get("Main_OpenInExplorer"); }
        }
        public static string Main_GrepThisFolder {
            get { return StringOverlay.Get("Main_GrepThisFolder"); }
        }
        public static string Main_List {
            get { return StringOverlay.Get("Main_List"); }
        }
        public static string Main_LargeIcons {
            get { return StringOverlay.Get("Main_LargeIcons"); }
        }
        public static string Main_SmallIcons {
            get { return StringOverlay.Get("Main_SmallIcons"); }
        }
        public static string Main_Physical {
            get { return StringOverlay.Get("Main_Physical"); }
        }
        public static string Main_Solution {
            get { return StringOverlay.Get("Main_Solution"); }
        }
        public static string Main_RemoveSettings {
            get { return StringOverlay.Get("Main_RemoveSettings"); }
        }
        public static string Main_IconRemove {
            get { return StringOverlay.Get("Main_IconRemove"); }
        }
        public static string Main_MftTooltip {
            get { return StringOverlay.Get("Main_MftTooltip"); }
        }
        public static string Main_Mft {
            get { return StringOverlay.Get("Main_Mft"); }
        }
        public static string Main_GrepTooltip {
            get { return StringOverlay.Get("Main_GrepTooltip"); }
        }
        public static string Main_Grep {
            get { return StringOverlay.Get("Main_Grep"); }
        }
        public static string Main_ApplyTooltip {
            get { return StringOverlay.Get("Main_ApplyTooltip"); }
        }
        public static string Main_IconApply {
            get { return StringOverlay.Get("Main_IconApply"); }
        }
        public static string Main_PreviewUnavailable {
            get { return StringOverlay.Get("Main_PreviewUnavailable"); }
        }
        public static string Main_IndexN {
            get { return StringOverlay.Get("Main_IndexN"); }
        }
        public static string Main_SelectSearchFolder {
            get { return StringOverlay.Get("Main_SelectSearchFolder"); }
        }
        public static string Main_FolderPickerFailed {
            get { return StringOverlay.Get("Main_FolderPickerFailed"); }
        }
        public static string Main_IconFilter {
            get { return StringOverlay.Get("Main_IconFilter"); }
        }
        public static string Main_SelectedSuffix {
            get { return StringOverlay.Get("Main_SelectedSuffix"); }
        }
        public static string Main_LibrarySelectFailed {
            get { return StringOverlay.Get("Main_LibrarySelectFailed"); }
        }
        public static string Main_ChooseLibraryFirst {
            get { return StringOverlay.Get("Main_ChooseLibraryFirst"); }
        }
        public static string Main_LoadingIcons {
            get { return StringOverlay.Get("Main_LoadingIcons"); }
        }
        public static string Main_NoIconGroups {
            get { return StringOverlay.Get("Main_NoIconGroups"); }
        }
        public static string Main_IconNSelected {
            get { return StringOverlay.Get("Main_IconNSelected"); }
        }
        public static string Main_IconCancelled {
            get { return StringOverlay.Get("Main_IconCancelled"); }
        }
        public static string Main_IconBrowserFailed {
            get { return StringOverlay.Get("Main_IconBrowserFailed"); }
        }
        public static string Main_LocationMissing {
            get { return StringOverlay.Get("Main_LocationMissing"); }
        }
        public static string Main_ReadingNtfs {
            get { return StringOverlay.Get("Main_ReadingNtfs"); }
        }
        public static string Main_IndexedFolders {
            get { return StringOverlay.Get("Main_IndexedFolders"); }
        }
        public static string Main_FastUnavailable {
            get { return StringOverlay.Get("Main_FastUnavailable"); }
        }
        public static string Main_FastPermissionUnavailable {
            get { return StringOverlay.Get("Main_FastPermissionUnavailable"); }
        }
        public static string Main_DriveIndexFailed {
            get { return StringOverlay.Get("Main_DriveIndexFailed"); }
        }
        public static string Main_FoldersAnalyzing {
            get { return StringOverlay.Get("Main_FoldersAnalyzing"); }
        }
        public static string Main_MatchesAnalyzing {
            get { return StringOverlay.Get("Main_MatchesAnalyzing"); }
        }
        public static string Main_SearchCancelled {
            get { return StringOverlay.Get("Main_SearchCancelled"); }
        }
        public static string Main_SearchFailed {
            get { return StringOverlay.Get("Main_SearchFailed"); }
        }
        public static string Main_ScanningFolders {
            get { return StringOverlay.Get("Main_ScanningFolders"); }
        }
        public static string Main_IndexedFoldersEllipsis {
            get { return StringOverlay.Get("Main_IndexedFoldersEllipsis"); }
        }
        public static string Main_BuildingTree {
            get { return StringOverlay.Get("Main_BuildingTree"); }
        }
        public static string Main_ElevationCancelled {
            get { return StringOverlay.Get("Main_ElevationCancelled"); }
        }
        public static string Main_ElevationFailed {
            get { return StringOverlay.Get("Main_ElevationFailed"); }
        }
        public static string Main_FoldersFound {
            get { return StringOverlay.Get("Main_FoldersFound"); }
        }
        public static string Main_SolutionsFound {
            get { return StringOverlay.Get("Main_SolutionsFound"); }
        }
        public static string Main_SearchResults {
            get { return StringOverlay.Get("Main_SearchResults"); }
        }
        public static string Main_NItems {
            get { return StringOverlay.Get("Main_NItems"); }
        }
        public static string Main_NFolders {
            get { return StringOverlay.Get("Main_NFolders"); }
        }
        public static string Main_NMatches {
            get { return StringOverlay.Get("Main_NMatches"); }
        }
        public static string Main_BuildingRows {
            get { return StringOverlay.Get("Main_BuildingRows"); }
        }
        public static string Main_LocationSet {
            get { return StringOverlay.Get("Main_LocationSet"); }
        }
        public static string Main_ExplorerFailed {
            get { return StringOverlay.Get("Main_ExplorerFailed"); }
        }
        public static string Main_FilesHeader {
            get { return StringOverlay.Get("Main_FilesHeader"); }
        }
        public static string Main_OpenFileFailed {
            get { return StringOverlay.Get("Main_OpenFileFailed"); }
        }
        public static string Main_SelectOneFolder {
            get { return StringOverlay.Get("Main_SelectOneFolder"); }
        }
        public static string Main_ConfirmApply {
            get { return StringOverlay.Get("Main_ConfirmApply"); }
        }
        public static string Main_AppliedTo {
            get { return StringOverlay.Get("Main_AppliedTo"); }
        }
        public static string Main_ApplyResult {
            get { return StringOverlay.Get("Main_ApplyResult"); }
        }
        public static string Main_ConfirmRemove {
            get { return StringOverlay.Get("Main_ConfirmRemove"); }
        }
        public static string Main_RemovedFrom {
            get { return StringOverlay.Get("Main_RemovedFrom"); }
        }
        public static string Main_RemoveResult {
            get { return StringOverlay.Get("Main_RemoveResult"); }
        }
        public static string Main_NoGrepFolders {
            get { return StringOverlay.Get("Main_NoGrepFolders"); }
        }
        public static string Main_RestoreTreesFailed {
            get { return StringOverlay.Get("Main_RestoreTreesFailed"); }
        }
        public static string Main_TreesRestored {
            get { return StringOverlay.Get("Main_TreesRestored"); }
        }
        public static string Main_SaveTreesFailed {
            get { return StringOverlay.Get("Main_SaveTreesFailed"); }
        }
        public static string Grep_Title {
            get { return StringOverlay.Get("Grep_Title"); }
        }
        public static string Grep_ScopeHint {
            get { return StringOverlay.Get("Grep_ScopeHint"); }
        }
        public static string Grep_ReloadSelection {
            get { return StringOverlay.Get("Grep_ReloadSelection"); }
        }
        public static string Grep_Reload {
            get { return StringOverlay.Get("Grep_Reload"); }
        }
        public static string Grep_SearchText {
            get { return StringOverlay.Get("Grep_SearchText"); }
        }
        public static string Grep_LanguageProfile {
            get { return StringOverlay.Get("Grep_LanguageProfile"); }
        }
        public static string Grep_IncludedExtensions {
            get { return StringOverlay.Get("Grep_IncludedExtensions"); }
        }
        public static string Grep_Regex {
            get { return StringOverlay.Get("Grep_Regex"); }
        }
        public static string Grep_MatchCase {
            get { return StringOverlay.Get("Grep_MatchCase"); }
        }
        public static string Grep_WholeWord {
            get { return StringOverlay.Get("Grep_WholeWord"); }
        }
        public static string Grep_Project {
            get { return StringOverlay.Get("Grep_Project"); }
        }
        public static string Grep_FileName {
            get { return StringOverlay.Get("Grep_FileName"); }
        }
        public static string Grep_Line {
            get { return StringOverlay.Get("Grep_Line"); }
        }
        public static string Grep_Column {
            get { return StringOverlay.Get("Grep_Column"); }
        }
        public static string Grep_Match {
            get { return StringOverlay.Get("Grep_Match"); }
        }
        public static string Grep_Editor {
            get { return StringOverlay.Get("Grep_Editor"); }
        }
        public static string Grep_EditorArguments {
            get { return StringOverlay.Get("Grep_EditorArguments"); }
        }
        public static string Grep_EditorExecutable {
            get { return StringOverlay.Get("Grep_EditorExecutable"); }
        }
        public static string Grep_BrowseEditor {
            get { return StringOverlay.Get("Grep_BrowseEditor"); }
        }
        public static string Icon_Title {
            get { return StringOverlay.Get("Icon_Title"); }
        }
        public static string Icon_Hint {
            get { return StringOverlay.Get("Icon_Hint"); }
        }
        public static string Mft_Title {
            get { return StringOverlay.Get("Mft_Title"); }
        }
        public static string Mft_CancelCompare {
            get { return StringOverlay.Get("Mft_CancelCompare"); }
        }
        public static string Mft_CompareDates {
            get { return StringOverlay.Get("Mft_CompareDates"); }
        }
        public static string Mft_CompareDatesTip {
            get { return StringOverlay.Get("Mft_CompareDatesTip"); }
        }
        public static string Mft_CleanTip {
            get { return StringOverlay.Get("Mft_CleanTip"); }
        }
        public static string Mft_CleanSolution {
            get { return StringOverlay.Get("Mft_CleanSolution"); }
        }
        public static string Mft_SourceToTarget {
            get { return StringOverlay.Get("Mft_SourceToTarget"); }
        }
        public static string Mft_TargetToSource {
            get { return StringOverlay.Get("Mft_TargetToSource"); }
        }
        public static string Mft_NeedRoots {
            get { return StringOverlay.Get("Mft_NeedRoots"); }
        }
        public static string Mft_SameTimeSize {
            get { return StringOverlay.Get("Mft_SameTimeSize"); }
        }
        public static string Mft_DifferentMeta {
            get { return StringOverlay.Get("Mft_DifferentMeta"); }
        }
        public static string Mft_SourceOnly {
            get { return StringOverlay.Get("Mft_SourceOnly"); }
        }
        public static string Mft_TargetOnly {
            get { return StringOverlay.Get("Mft_TargetOnly"); }
        }
        public static string Mft_ShowObj {
            get { return StringOverlay.Get("Mft_ShowObj"); }
        }
        public static string Mft_ShowBin {
            get { return StringOverlay.Get("Mft_ShowBin"); }
        }
        public static string Mft_NotCompared {
            get { return StringOverlay.Get("Mft_NotCompared"); }
        }
        public static string Mft_Selected {
            get { return StringOverlay.Get("Mft_Selected"); }
        }
        public static string Mft_SelectedIncludesHidden {
            get { return StringOverlay.Get("Mft_SelectedIncludesHidden"); }
        }
        public static string Mft_AllFolders {
            get { return StringOverlay.Get("Mft_AllFolders"); }
        }
        public static string Mft_FilesAllLevels {
            get { return StringOverlay.Get("Mft_FilesAllLevels"); }
        }
        public static string Mft_SyncTitle {
            get { return StringOverlay.Get("Mft_SyncTitle"); }
        }
        public static string Mft_SyncSelectedTitle {
            get { return StringOverlay.Get("Mft_SyncSelectedTitle"); }
        }
        public static string Mft_OverwriteWarning {
            get { return StringOverlay.Get("Mft_OverwriteWarning"); }
        }
        public static string Mft_Synchronize {
            get { return StringOverlay.Get("Mft_Synchronize"); }
        }
        public static string Mft_Synchronizing {
            get { return StringOverlay.Get("Mft_Synchronizing"); }
        }
        public static string Mft_SourceLabel {
            get { return StringOverlay.Get("Mft_SourceLabel"); }
        }
        public static string Mft_TargetLabel {
            get { return StringOverlay.Get("Mft_TargetLabel"); }
        }
        public static string Mft_Syncing {
            get { return StringOverlay.Get("Mft_Syncing"); }
        }
        public static string Mft_FailPrefix {
            get { return StringOverlay.Get("Mft_FailPrefix"); }
        }
        public static string Mft_LogLabel {
            get { return StringOverlay.Get("Mft_LogLabel"); }
        }
        public static string Mft_SaveLogFailed {
            get { return StringOverlay.Get("Mft_SaveLogFailed"); }
        }
        public static string Mft_CompleteCounts {
            get { return StringOverlay.Get("Mft_CompleteCounts"); }
        }
        public static string Mft_SyncResultTitle {
            get { return StringOverlay.Get("Mft_SyncResultTitle"); }
        }
        public static string Mft_DiffView {
            get { return StringOverlay.Get("Mft_DiffView"); }
        }
        public static string Mft_SaveTreeFailed {
            get { return StringOverlay.Get("Mft_SaveTreeFailed"); }
        }
        public static string Mft_CompareCancelled {
            get { return StringOverlay.Get("Mft_CompareCancelled"); }
        }
        public static string Mft_CompareFailed {
            get { return StringOverlay.Get("Mft_CompareFailed"); }
        }
        public static string Mft_DifferencesSummary {
            get { return StringOverlay.Get("Mft_DifferencesSummary"); }
        }
        public static string Mft_ProgressItems {
            get { return StringOverlay.Get("Mft_ProgressItems"); }
        }
        public static string Mft_UpdatingTree {
            get { return StringOverlay.Get("Mft_UpdatingTree"); }
        }
        public static string Mft_ReadingMeta {
            get { return StringOverlay.Get("Mft_ReadingMeta"); }
        }
        public static string Mft_Classifying {
            get { return StringOverlay.Get("Mft_Classifying"); }
        }
        public static string Mft_ReadingMftFor {
            get { return StringOverlay.Get("Mft_ReadingMftFor"); }
        }
        public static string Mft_MftUnavailableFor {
            get { return StringOverlay.Get("Mft_MftUnavailableFor"); }
        }
        public static string Mft_ScanWithoutMft {
            get { return StringOverlay.Get("Mft_ScanWithoutMft"); }
        }
        public static string Mft_ScanComplete {
            get { return StringOverlay.Get("Mft_ScanComplete"); }
        }
        public static string Mft_FileDisappeared {
            get { return StringOverlay.Get("Mft_FileDisappeared"); }
        }
        public static string Mft_SkipSame {
            get { return StringOverlay.Get("Mft_SkipSame"); }
        }
        public static string Mft_ChangedAfterCompare {
            get { return StringOverlay.Get("Mft_ChangedAfterCompare"); }
        }
        public static string Mft_ChangedDuringCopy {
            get { return StringOverlay.Get("Mft_ChangedDuringCopy"); }
        }
        public static string Mft_VerifyFailed {
            get { return StringOverlay.Get("Mft_VerifyFailed"); }
        }
        public static string Mft_ChooseLocalRoot {
            get { return StringOverlay.Get("Mft_ChooseLocalRoot"); }
        }
        public static string Mft_RootsNested {
            get { return StringOverlay.Get("Mft_RootsNested"); }
        }
        public static string Mft_ProtectedPath {
            get { return StringOverlay.Get("Mft_ProtectedPath"); }
        }
        public static string Mft_RefusedPath {
            get { return StringOverlay.Get("Mft_RefusedPath"); }
        }
        public static string Mft_LinkExcluded {
            get { return StringOverlay.Get("Mft_LinkExcluded"); }
        }
        public static string Mft_NotRegularFile {
            get { return StringOverlay.Get("Mft_NotRegularFile"); }
        }
        public static string Mft_Bytes {
            get { return StringOverlay.Get("Mft_Bytes"); }
        }
        public static string Mft_StateTargetOnly {
            get { return StringOverlay.Get("Mft_StateTargetOnly"); }
        }
        public static string Mft_StateSourceOnly {
            get { return StringOverlay.Get("Mft_StateSourceOnly"); }
        }
        public static string Mft_StateSizeDiffers {
            get { return StringOverlay.Get("Mft_StateSizeDiffers"); }
        }
        public static string Mft_StateTimeSizeDiffers {
            get { return StringOverlay.Get("Mft_StateTimeSizeDiffers"); }
        }
        public static string Mft_StateSame {
            get { return StringOverlay.Get("Mft_StateSame"); }
        }
        public static string Mft_StateNew {
            get { return StringOverlay.Get("Mft_StateNew"); }
        }
        public static string Mft_StateOld {
            get { return StringOverlay.Get("Mft_StateOld"); }
        }
        public static string Diff_Title {
            get { return StringOverlay.Get("Diff_Title"); }
        }
        public static string Diff_Fit {
            get { return StringOverlay.Get("Diff_Fit"); }
        }
        public static string Diff_ActualSize {
            get { return StringOverlay.Get("Diff_ActualSize"); }
        }
        public static string Diff_BinaryRejected {
            get { return StringOverlay.Get("Diff_BinaryRejected"); }
        }
        public static string Err_FileNotFound {
            get { return StringOverlay.Get("Err_FileNotFound"); }
        }
        public static string Err_FileLabel {
            get { return StringOverlay.Get("Err_FileLabel"); }
        }
        public static string Err_DirectoryNotFound {
            get { return StringOverlay.Get("Err_DirectoryNotFound"); }
        }
        public static string Err_DriveNotFound {
            get { return StringOverlay.Get("Err_DriveNotFound"); }
        }
        public static string Err_AccessDenied {
            get { return StringOverlay.Get("Err_AccessDenied"); }
        }
        public static string Err_PathTooLong {
            get { return StringOverlay.Get("Err_PathTooLong"); }
        }
        public static string Err_FileLocked {
            get { return StringOverlay.Get("Err_FileLocked"); }
        }
        public static string Err_Generic {
            get { return StringOverlay.Get("Err_Generic"); }
        }
        public static string Grep_CancelBeforeChange {
            get { return StringOverlay.Get("Grep_CancelBeforeChange"); }
        }
        public static string Grep_FolderSingular {
            get { return StringOverlay.Get("Grep_FolderSingular"); }
        }
        public static string Grep_FolderPlural {
            get { return StringOverlay.Get("Grep_FolderPlural"); }
        }
        public static string Grep_NoFoldersSelected {
            get { return StringOverlay.Get("Grep_NoFoldersSelected"); }
        }
        public static string Grep_SelectFolders {
            get { return StringOverlay.Get("Grep_SelectFolders"); }
        }
        public static string Grep_EnterText {
            get { return StringOverlay.Get("Grep_EnterText"); }
        }
        public static string Grep_EnterExtensions {
            get { return StringOverlay.Get("Grep_EnterExtensions"); }
        }
        public static string Grep_SearchingFiles {
            get { return StringOverlay.Get("Grep_SearchingFiles"); }
        }
        public static string Grep_Result {
            get { return StringOverlay.Get("Grep_Result"); }
        }
        public static string Grep_ResultSkipped {
            get { return StringOverlay.Get("Grep_ResultSkipped"); }
        }
        public static string Grep_SearchCancelled {
            get { return StringOverlay.Get("Grep_SearchCancelled"); }
        }
        public static string Grep_InvalidExpression {
            get { return StringOverlay.Get("Grep_InvalidExpression"); }
        }
        public static string Grep_InvalidExpressionStatus {
            get { return StringOverlay.Get("Grep_InvalidExpressionStatus"); }
        }
        public static string Grep_SearchFailed {
            get { return StringOverlay.Get("Grep_SearchFailed"); }
        }
        public static string Grep_EditorFailed {
            get { return StringOverlay.Get("Grep_EditorFailed"); }
        }
        public static string Grep_EditorFilter {
            get { return StringOverlay.Get("Grep_EditorFilter"); }
        }
        public static string Grep_Cancelling {
            get { return StringOverlay.Get("Grep_Cancelling"); }
        }
        public static string Icon_NIcons {
            get { return StringOverlay.Get("Icon_NIcons"); }
        }
        public static string Diff_BinaryMessage {
            get { return StringOverlay.Get("Diff_BinaryMessage"); }
        }
        public static string Diff_TitleFile {
            get { return StringOverlay.Get("Diff_TitleFile"); }
        }
        public static string Diff_Heading {
            get { return StringOverlay.Get("Diff_Heading"); }
        }
        public static string Diff_Prev {
            get { return StringOverlay.Get("Diff_Prev"); }
        }
        public static string Diff_Next {
            get { return StringOverlay.Get("Diff_Next"); }
        }
        public static string Diff_OpenSource {
            get { return StringOverlay.Get("Diff_OpenSource"); }
        }
        public static string Diff_OpenTarget {
            get { return StringOverlay.Get("Diff_OpenTarget"); }
        }
        public static string Diff_Loading {
            get { return StringOverlay.Get("Diff_Loading"); }
        }
        public static string Diff_HunkStatus {
            get { return StringOverlay.Get("Diff_HunkStatus"); }
        }
        public static string Diff_Unable {
            get { return StringOverlay.Get("Diff_Unable"); }
        }
        public static string Diff_TooLargeBytes {
            get { return StringOverlay.Get("Diff_TooLargeBytes"); }
        }
        public static string Diff_TooManyLines {
            get { return StringOverlay.Get("Diff_TooManyLines"); }
        }
        public static string Diff_ZoomShared {
            get { return StringOverlay.Get("Diff_ZoomShared"); }
        }
        public static string Diff_Zoom {
            get { return StringOverlay.Get("Diff_Zoom"); }
        }
        public static string Diff_ImageStatus {
            get { return StringOverlay.Get("Diff_ImageStatus"); }
        }
        public static string Diff_Missing {
            get { return StringOverlay.Get("Diff_Missing"); }
        }
        public static string Diff_None {
            get { return StringOverlay.Get("Diff_None"); }
        }
        public static string Diff_Pixels {
            get { return StringOverlay.Get("Diff_Pixels"); }
        }
        public static string Diff_SourceMissing {
            get { return StringOverlay.Get("Diff_SourceMissing"); }
        }
        public static string Diff_TargetMissing {
            get { return StringOverlay.Get("Diff_TargetMissing"); }
        }
        public static string Diff_HunkN {
            get { return StringOverlay.Get("Diff_HunkN"); }
        }
        public static string Diff_VisibleRange {
            get { return StringOverlay.Get("Diff_VisibleRange"); }
        }
        public static string Mft_FindingSolutions {
            get { return StringOverlay.Get("Mft_FindingSolutions"); }
        }
        public static string Mft_NoSolutions {
            get { return StringOverlay.Get("Mft_NoSolutions"); }
        }
        public static string Mft_CleanSolutionsTitle {
            get { return StringOverlay.Get("Mft_CleanSolutionsTitle"); }
        }
        public static string Mft_CleanDialogHint {
            get { return StringOverlay.Get("Mft_CleanDialogHint"); }
        }
        public static string Mft_ConfigurationsLabel {
            get { return StringOverlay.Get("Mft_ConfigurationsLabel"); }
        }
        public static string Mft_DimLockedTip {
            get { return StringOverlay.Get("Mft_DimLockedTip"); }
        }
        public static string Mft_SourceLeft {
            get { return StringOverlay.Get("Mft_SourceLeft"); }
        }
        public static string Mft_TargetRight {
            get { return StringOverlay.Get("Mft_TargetRight"); }
        }
        public static string Mft_SelectSolutions {
            get { return StringOverlay.Get("Mft_SelectSolutions"); }
        }
        public static string Mft_CleanCancelled {
            get { return StringOverlay.Get("Mft_CleanCancelled"); }
        }
        public static string Mft_Cleaning {
            get { return StringOverlay.Get("Mft_Cleaning"); }
        }
        public static string Mft_FailExit {
            get { return StringOverlay.Get("Mft_FailExit"); }
        }
        public static string Mft_CleanComplete {
            get { return StringOverlay.Get("Mft_CleanComplete"); }
        }
        public static string Mft_CleanFailed {
            get { return StringOverlay.Get("Mft_CleanFailed"); }
        }
        public static string Mft_PreviewUnavailable {
            get { return StringOverlay.Get("Mft_PreviewUnavailable"); }
        }
        public static string Mft_FilterSummary {
            get { return StringOverlay.Get("Mft_FilterSummary"); }
        }
        public static string Mft_RestoredClickCompare {
            get { return StringOverlay.Get("Mft_RestoredClickCompare"); }
        }
        public static string Mft_RestoreTreeFailed {
            get { return StringOverlay.Get("Mft_RestoreTreeFailed"); }
        }
        public static string Mft_SourceFolder {
            get { return StringOverlay.Get("Mft_SourceFolder"); }
        }
        public static string Mft_TargetFolder {
            get { return StringOverlay.Get("Mft_TargetFolder"); }
        }
        public static string Mft_CancellingCompare {
            get { return StringOverlay.Get("Mft_CancellingCompare"); }
        }
        public static string Mft_Enumerating {
            get { return StringOverlay.Get("Mft_Enumerating"); }
        }
        public static string Clean_VswhereMissing {
            get { return StringOverlay.Get("Clean_VswhereMissing"); }
        }
        public static string Clean_MsbuildMissing {
            get { return StringOverlay.Get("Clean_MsbuildMissing"); }
        }
        public static string Clean_RunningDim {
            get { return StringOverlay.Get("Clean_RunningDim"); }
        }
        public static string Clean_BadConfiguration {
            get { return StringOverlay.Get("Clean_BadConfiguration"); }
        }
        public static string Mft_HardLinkExcluded {
            get { return StringOverlay.Get("Mft_HardLinkExcluded"); }
        }
        public static string Mft_OkPrefix {
            get { return StringOverlay.Get("Mft_OkPrefix"); }
        }
        public static string Mft_LockedPrefix {
            get { return StringOverlay.Get("Mft_LockedPrefix"); }
        }
        public static string Main_ApplyOk {
            get { return StringOverlay.Get("Main_ApplyOk"); }
        }
        public static string Main_RemoveOk {
            get { return StringOverlay.Get("Main_RemoveOk"); }
        }
        public static string Main_ElevationTooltip {
            get { return StringOverlay.Get("Main_ElevationTooltip"); }
        }
    }
}
